[build]
  base = "."
  publish = "dist"
  command = "npm run build"

# Configure secrets scanning to ignore Firebase keys and README.md
# Firebase client-side keys are intentionally public (restricted by Firebase domain rules)
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID,VITE_FIREBASE_MEASUREMENT_ID,VITE_GEMINI_API_KEY,apiKey,authDomain,projectId,storageBucket,messagingSenderId,appId,measurementId"
  SECRETS_SCAN_OMIT_PATHS = "README.md"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

