[build]
  base = "."
  publish = "dist"
  command = "npm run build"

# Note: Firebase client-side keys are intentionally public (restricted by Firebase domain rules)
# To disable secrets scanning, go to Netlify Dashboard → Site Settings → Build & Deploy → Security
# And mark these as false positives or disable secrets scanning for this site

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

