[build]
  base = "project"
  publish = "project/dist"
  command = "npm run build"

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyDIgwHL2_oAbcTr9jpGcURnTseIaAkica4"
  VITE_FIREBASE_AUTH_DOMAIN = "ai-edu-graduates.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "ai-edu-graduates"
  VITE_FIREBASE_STORAGE_BUCKET = "ai-edu-graduates.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "745004327373"
  VITE_FIREBASE_APP_ID = "1:745004327373:web:3fa580fdda4cc48080e484"
  VITE_FIREBASE_MEASUREMENT_ID = "G-2FDRK3JRBV"
  VITE_GEMINI_API_KEY = "your_gemini_api_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
